Fall back to SAN for certificates without a CN

diff --git a/templates/install_certificates.sh.j2 b/templates/install_certificates.sh.j2
--- a/templates/install_certificates.sh.j2
+++ b/templates/install_certificates.sh.j2
@@ -12,7 +12,7 @@
 # certificate file. Other than that, file names can be arbitrary and do not
 # need to be consistent between invocations of this script.
 # Files in the target directory are named consistently, based on the
-# certificate's CN filed. File names are:
+# certificate's CN or first SAN filed. File names are:
 # * ${cn}.pem
 # * ${cn}.key
 # * ${cn}_chain.pem
@@ -99,8 +99,12 @@ install_certificate() {
     target_bundled_file="${target_dir}/${cn}_fullchain.pem"
 
     if [ -z "${cn}" ] || [ "${cn#*=}" != "${cn}" ]; then
-        log err "Could not parse CN field. Skipping ${cert_file#${tmp_dir%/}/}."
-        exit 1
+        # No CN. The certificate may not have one. Fall back to the first DNS name from the subject alternative name extension.
+        cn="$(LC_ALL=POSIX openssl x509 -in "${cert_file}" -noout -ext subjectAltName | sed -Ene 's/.*DNS:([a-z0-9.-]{1,255})(,.*)?/\1/Ip')"
+        if [ -z "${cn}" ]; then
+            log err "Could not parse CN field or subject alternative name. Skipping ${cert_file#${tmp_dir%/}/}."
+            exit 1
+        fi
     fi
 
     log debug "CN=${cn}, Issuer: ${issuer}"
